# Generated by Django 5.0.2 on 2024-02-10 15:28

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFlashcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('usuario_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_frente', models.CharField(max_length=255)),
                ('traducao_verso', models.CharField(max_length=255)),
                ('frase_aplicacao_verso', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('info_adicional', models.TextField()),
                ('opcoes_revisao', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=4)),
                ('girar_flashcard', models.BooleanField(default=True)),
                ('usuario_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo_pertencente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.grupoflashcards')),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_flashcards_revisados', models.IntegerField()),
                ('quantidade_acertos', models.IntegerField()),
                ('quantidade_erros', models.IntegerField()),
                ('grupo_flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.grupoflashcards')),
            ],
        ),
    ]
