# Generated by Django 5.0.2 on 2024-02-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoflashcards',
            name='flashcards',
            field=models.ManyToManyField(to='flashcard.flashcard'),
        ),
    ]
