# Generated by Django 5.0.2 on 2024-02-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_grupoflashcards_flashcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoflashcards',
            name='flashcards',
        ),
    ]
