# Generated by Django 5.0.2 on 2024-02-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_remove_grupoflashcards_flashcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='grupo_pertencente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard.grupoflashcards'),
        ),
    ]
