# Generated by Django 5.0.2 on 2024-02-15 01:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_flashcard_grupo_pertencente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoFlashcards',
            new_name='GrupoFlashcard',
        ),
    ]
