# Generated by Django 5.0.2 on 2024-02-17 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_rename_grupoflashcards_grupoflashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='frase_aplicacao_verso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='info_adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='opcoes_revisao',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='traducao_verso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
