# Generated by Django 5.0.2 on 2024-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_alter_flashcard_opcoes_revisao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='frase_aplicacao_verso',
            new_name='frase_aplicacao_verso_original',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='frase_aplicacao_verso_traduzida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
