# Generated by Django 5.0.2 on 2024-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_rename_frase_aplicacao_verso_flashcard_frase_aplicacao_verso_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='info_adicional',
            field=models.TextField(blank=True, default='Sem informações adicionais', null=True),
        ),
    ]
